-------------------------------------------
-- $HeadURL: $
-- $Date: $
-- CEMLI ID: PO.02.11
-- Script: XXPO_PO_INTERFACE_STG_DDL.sql
-- Author: Dart Arellano DXC Red Rock
-------------------------------------------

CREATE OR REPLACE VIEW xxpo_po_interface_stg
AS
SELECT s.control_id,
       s.file_name,
       h.order_number,
       h.order_type,
       h.status,
       h.supplier_id,
       h.supplier_code,
       h.supplier_name,
       h.creation_date,
       h.created_by,
       h.payment_term_code,
       h.payment_term_name,
       h.gross_sum,
       h.net_sum,
       h.owner,
       h.purpose,
       h.company_code,
       h.purchase_currency,
       h.desired_delivery_enddate,
       l.line_number,
       l.note_to_vendor,
       l.promised_date,
       l.need_by_date,
       l.contract_num,
       l.note_to_receiver,
       l.item_description,
       l.rate,
       l.unit_of_measure,
       l.quantity,
       l.amount,
       l.tax_name,
       l.category_code,
       l.vendor_product_num,
       l.expiration_date,
       d.account_segment1,
       '999' account_segment2,
       d.account_segment3,
       d.account_segment4,
       d.account_segment5,
       d.account_segment6,
       d.distribution_num,
       d.split_percent,
       d.attribute1
FROM   xxfnd_interface_stg s,
       XMLTable('/Order' PASSING s.file_content 
                COLUMNS order_number              VARCHAR2(150) PATH 'OrderNumber',
                        order_type                VARCHAR2(150) PATH 'OrderType',
                        status                    VARCHAR2(150) PATH 'OrderStatus',
                        supplier_id               VARCHAR2(150) PATH 'SupplierId',
                        supplier_code             VARCHAR2(150) PATH 'SupplierCode',
                        supplier_name             VARCHAR2(150) PATH 'SupplierName',
                        creation_date             VARCHAR2(150) PATH 'CreationTime',
                        created_by                VARCHAR2(150) PATH 'CreatorId',
                        payment_term_code         VARCHAR2(150) PATH 'PaymentTermCode',
                        payment_term_name         VARCHAR2(150) PATH 'PaymentTermName',
                        gross_sum                 VARCHAR2(150) PATH 'GrossSum',
                        net_sum                   VARCHAR2(150) PATH 'NetSum',
                        owner                     VARCHAR2(150) PATH 'Owner',
                        purpose                   VARCHAR2(150) PATH 'Purpose',
                        company_code              VARCHAR2(150) PATH 'CompanyCode',
                        purchase_currency         VARCHAR2(150) PATH 'PurchaseCurrency',
                        desired_delivery_enddate  VARCHAR2(150) PATH 'DesiredDeliveryEndDate',
                        orderline                 XMLType       PATH 'OrderRows/OrderLine') h,
       XMLTable('OrderLine' PASSING h.orderline 
                COLUMNS line_number               VARCHAR2(150) PATH 'LineNumber',
                        note_to_vendor            VARCHAR2(150) PATH 'Note',
                        promised_date             VARCHAR2(150) PATH 'PromisedDeliveryDate',
                        need_by_date              VARCHAR2(150) PATH 'DesiredDeliveryDate',
                        contract_num              VARCHAR2(150) PATH 'ContractNumber',
                        note_to_receiver          VARCHAR2(480) PATH 'NoteFromSupplier',
                        item_description          VARCHAR2(240) PATH 'Description',
                        rate                      VARCHAR2(150) PATH 'ExchangeRateComp',
                        unit_of_measure           VARCHAR2(150) PATH 'QuantityUnitName',
                        quantity                  VARCHAR2(150) PATH 'Quantity',
                        amount                    VARCHAR2(150) PATH 'NetSum',
                        tax_name                  VARCHAR2(150) PATH 'TaxCode',
                        category_code             VARCHAR2(150) PATH 'CategoryCode',
                        vendor_product_num        VARCHAR2(150) PATH 'OrderSupplierProductCode',
                        expiration_date           VARCHAR2(150) PATH 'DesiredDeliveryEndDate',
                        codingrow                 XMLType       PATH 'CodingRows/CodingRow') l,
       XMLTable('CodingRow' PASSING l.codingrow 
                COLUMNS account_segment1          VARCHAR2(150) PATH 'CompanyCode', 
                        account_segment3          VARCHAR2(150) PATH 'CostCenterCode',
                        account_segment4          VARCHAR2(150) PATH 'AccountCode',
                        account_segment5          VARCHAR2(150) PATH 'ProjectCode',
                        account_segment6          VARCHAR2(150) PATH 'LineDataText4',
                        distribution_num          VARCHAR2(150) PATH 'RowIndex',
                        split_percent             VARCHAR2(150) PATH 'SplitPercent',
                        attribute1                VARCHAR2(150) PATH 'LineDataText5') d
WHERE  s.object_type = 'ORDER'
AND    s.in_out = 'IN';
